name: disign_shopping
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0-174.2.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true

  assets:
   - assets/slide1.png
   - assets/slide3.png
  #  - assets/slide4.png
   - assets/icon1.png
   - assets/icon2.png
   - assets/icon3.png
   - assets/icon4.png
   - assets/icon5.png
   - assets/icon6.png
   - assets/icon7.png
   - assets/Маасы.png
   - assets/Галош.png
   - assets/Балдардыкы.png
   - assets/Туфли.png
   - assets/p1.png
   - assets/p2.png 
   - assets/p3.png 
   - assets/p4.png
   - assets/p5.png 
   - assets/p6.png 
   - assets/p7.png
   - assets/p8.png 



    # - lib/images/slide1.png
    # - lib/images/slide2.png
    # - lib/images/slide3.png
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
